apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cowsay-ui
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowsay-ui
  template:
    metadata:
      labels:
        app: cowsay-ui
    spec:
      containers:
      - name: cowsay-ui
        image: asia.gcr.io/fortune-teller-215315/fortune-teller-ui@sha256:416792ad7f37af47c1f775d6289ab63744df90fe7afd3cd3fcb5c8dc7b96270c 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
             cpu: 50m
             memory: 500Mi
          requests:
             cpu: 50m
             memory: 500Mi
        env:
          - name: COWSAY_SERVER_NAME
            value: 'cowsay'
          - name: COWSAY_SERVER_PORT
            value: '8000'
          - name: REDIS_SERVER_NAME
            value: 'redis-master'
          - name: REDIS_SERVER_PORT
            value: '6379'
