apiVersion: v1
kind: Service
metadata:
  name: cowsay
  namespace: web
  labels: 
    app: cowsay
spec:
  ports:
     - name: http
       protocol: TCP
       port: 8000
       targetPort: http
  selector:
      app: cowsay
