apiVersion: v1
kind: Service
metadata:
  name: cowsay-ui
  labels: 
    app: cowsay-ui
spec:
  type: LoadBalancer
  ports:
     - name: http
       protocol: TCP
       port: 80
       targetPort: http
  selector:
      app: cowsay-ui
